spring:
    application:
        name: spring-security
    datasource:
        url: ${DB_URL_MYSQL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            maximum-pool-size: 10
            max-lifetime: 60000
            connection-timeout: 100000
            idle-timeout: 100000
    jpa:
        database: MYSQL
        generate-ddl: true
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect   
                format_sql: true      

server:
    port: 8080
authorization:
    key: secretkey
